# Generated by Django 5.1.4 on 2025-08-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0025_adminphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='upi_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
