# Generated by Django 5.1.4 on 2025-08-13 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0026_depositrequest_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='related_withdraw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stapp.withdrawrequest'),
        ),
    ]
