# Generated by Django 5.1.4 on 2025-08-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0027_transaction_related_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='upi_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
