# Generated by Django 5.1.4 on 2025-08-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stapp', '0028_withdrawrequest_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminphoto',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
